Update LCD35-show

diff --git a/LCD35-show b/LCD35-show
--- a/LCD35-show
+++ b/LCD35-show
@@ -1,143 +1,100 @@
 #!/bin/bash
 
-sudo ./system_backup.sh
+# Exit on any error
+set -e
 
-if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
-sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
-fi
-if [ ! -d /etc/X11/xorg.conf.d ]; then
-sudo mkdir -p /etc/X11/xorg.conf.d
-fi
-sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/
-sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo
-#root_dev=`grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{printf $NF}'`
-#if test "$root_dev" = "/dev/mmcblk0p7";then
-#sudo cp -rf ./boot/config-noobs-nomal.txt ./boot/config.txt.bak
-#else
-#sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
-#sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
-#fi
+# Colors for output
+RED='\033[31m'
+GREEN='\033[32m'
+NC='\033[0m'
 
-source ./system_config.sh
-#sudo sed -i -e 's/dtoverlay=vc4-kms-v3d/#dtoverlay=vc4-kms-v3d/' ./boot/config.txt.bak
-sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
-sudo echo "dtparam=i2c_arm=on" >> ./boot/config.txt.bak
-sudo echo "dtparam=spi=on" >> ./boot/config.txt.bak
-sudo echo "enable_uart=1" >> ./boot/config.txt.bak
-sudo echo "dtoverlay=tft35a:rotate=90" >> ./boot/config.txt.bak
-sudo echo "hdmi_group=2" >> ./boot/config.txt.bak
-sudo echo "hdmi_mode=1" >> ./boot/config.txt.bak
-sudo echo "hdmi_mode=87" >> ./boot/config.txt.bak
-sudo echo "hdmi_cvt 480 320 60 6 0 0 0" >> ./boot/config.txt.bak
-sudo echo "hdmi_drive=2" >> ./boot/config.txt.bak
-sudo cp -rf ./boot/config.txt.bak /boot/config.txt
-
-sudo cp -rf ./usr/99-calibration.conf-35-90  /etc/X11/xorg.conf.d/99-calibration.conf
-if [[ "$deb_version" < "12.1" ]]; then
-sudo cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
+# Check if running as root
+if [ "$EUID" -ne 0 ]; then
+    echo "${RED}Please run as root (sudo ./LCD35-show)${NC}"
+    exit 1
 fi
-#if test "$root_dev" = "/dev/mmcblk0p7";then
-#sudo cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
-#else
-#sudo cp ./usr/cmdline.txt /boot/
-#fi
-sudo cp ./usr/inittab /etc/
-#sudo cp ./boot/config-35.txt /boot/config.txt
-sudo touch ./.have_installed
-echo "gpio:resistance:35:90:480:320" > ./.have_installed
 
-sudo apt-get update
-#FBCP install
-wget --spider -q -o /dev/null --tries=1 -T 10 https://cmake.org/
-if [ $? -eq 0 ]; then
-#sudo apt-get update
-sudo apt-get install cmake libraspberrypi-dev -y 2> error_output.txt
-result=`cat ./error_output.txt`
-echo -e "\033[31m$result\033[0m"
-grep -q "^E:" ./error_output.txt
-type cmake > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-sudo rm -rf rpi-fbcp
-wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
-if [ $? -eq 0 ]; then
-sudo git clone https://github.com/tasanakorn/rpi-fbcp
-if [ $? -ne 0 ]; then
-echo "download fbcp failed, copy native fbcp!!!"
-sudo cp -r ./usr/rpi-fbcp .
-fi
+# Detect architecture (Pi 3B defaults to 32-bit unless 64-bit OS is used)
+ARCH=$(uname -m)
+if [ "$ARCH" = "aarch64" ]; then
+    hardware_arch=64
+    echo "${GREEN}Detected 64-bit system${NC}"
 else
-echo "bad network, copy native fbcp!!!"
-sudo cp -r ./usr/rpi-fbcp .
-fi
-sudo mkdir ./rpi-fbcp/build
-cd ./rpi-fbcp/build/
-sudo cmake ..
-sudo make
-sudo install fbcp /usr/local/bin/fbcp
-cd - > /dev/null
-type fbcp > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-if [[ "$deb_version" < "12.1" ]]; then
-sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
-fi
-sudo cp -rf ./etc/rc.local /etc/rc.local
-fi
-else
-echo "install cmake error!!!!"
-fi
-else
-echo "bad network, can't install cmake!!!"
+    hardware_arch=32
+    echo "${GREEN}Detected 32-bit system (default for Pi 3B)${NC}"
 fi
 
-#evdev install
-#nodeplatform=`uname -n`
-#kernel=`uname -r`
-version=`uname -v`
-#if test "$nodeplatform" = "raspberrypi";then
-#echo "this is raspberrypi kernel"
-input_result=0
-version=${version##* }
-#version=${version#*#}
-echo $version
-if test $version -lt 2017;then
-echo "reboot"
-else
-echo "need to update touch configuration"
-wget --spider -q -o /dev/null --tries=1 -T 10 http://mirrors.zju.edu.cn/raspbian/raspbian
-if [ $? -ne 0 ]; then
-input_result=1
-else
-sudo apt-get install xserver-xorg-input-evdev  2> error_output.txt
-dpkg -l | grep xserver-xorg-input-evdev > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-input_result=1
-fi
-fi
-if [ $input_result -eq 1 ]; then 
-if [ $hardware_arch -eq 32 ]; then
-sudo dpkg -i -B ./xserver-xorg-input-evdev_1%3a2.10.6-1+b1_armhf.deb 2> error_output.txt
-elif [ $hardware_arch -eq 64 ]; then
-sudo dpkg -i -B ./xserver-xorg-input-evdev_1%3a2.10.6-2_arm64.deb 2> error_output.txt
-fi
-fi
-result=`cat ./error_output.txt`
-echo -e "\033[31m$result\033[0m"
-grep -q "error:" ./error_output.txt && exit
-sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
-#echo "reboot"
-fi
-#else
-#echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
-#fi
+# Backup system files
+echo "Backing up system files..."
+[ -f ./system_backup.sh ] && ./system_backup.sh || { echo "${RED}Backup script missing, proceeding without backup${NC}"; }
 
-sudo sync
-sudo sync
-sleep 1
-if [ $# -eq 1 ]; then
-sudo ./rotate.sh $1
-elif [ $# -gt 1 ]; then
-echo "Too many parameters"
-fi
+# Ensure X11 config directory exists and clean up old configs
+echo "Setting up X11 configuration..."
+[ -f /etc/X11/xorg.conf.d/40-libinput.conf ] && rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
+mkdir -p /etc/X11/xorg.conf.d
 
-echo "reboot now"
-sudo reboot
+# Copy overlay for TFT35A
+echo "Installing TFT35A overlay..."
+cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo || { echo "${RED}Failed to copy overlay!${NC}"; exit 1; }
+
+# Source system config or set defaults
+[ -f ./system_config.sh ] && source ./system_config.sh || { echo "${RED}system_config.sh missing, using defaults${NC}"; deb_version="12"; }
+
+# Update /boot/config.txt
+echo "Configuring /boot/config.txt for Pi 3B..."
+CONFIG_FILE="/boot/config.txt.bak"
+cp /boot/config.txt "$CONFIG_FILE" || { echo "${RED}Config backup failed!${NC}"; exit 1; }
+cat <<EOF > "$CONFIG_FILE"
+# Base config (preserve existing settings, append LCD-specific ones)
+$(grep -vE '^(dtparam|dtoverlay|hdmi_|framebuffer_)' /boot/config.txt || true)
+
+# TFT35A LCD Settings optimized for Pi 3B
+dtparam=i2c_arm=on
+dtparam=spi=on
+dtparam=spi_speed=50000000  # 50 MHz for Pi 3B stability and framerate boost
+enable_uart=1
+dtoverlay=tft35a:rotate=90
+framebuffer_width=480
+framebuffer_height=320
+EOF
+
+# Prompt for HDMI mirroring
+echo "Do you want HDMI to mirror the LCD? (y/n, default: n)"
+read -t 10 -r hdmi_choice || hdmi_choice="n"
+if [ "$hdmi_choice" = "y" ] || [ "$hdmi_choice" = "Y" ]; then
+    cat <<EOF >> "$CONFIG_FILE"
+# HDMI mirroring enabled
+hdmi_force_hotplug=1
+hdmi_group=2
+hdmi_mode=87
+hdmi_cvt 480 320 60 6 0 0 0
+hdmi_drive=2
+EOF
+else
+    cat <<EOF >> "$CONFIG_FILE"
+# HDMI disabled
+hdmi_force_hotplug=0
+EOF
+fi
+mv "$CONFIG_FILE" /boot/config.txt
+
+# Install X configuration
+echo "Configuring X server for LCD..."
+apt-get update -y
+apt-get install -y xserver-xorg-video-fbdev || { echo "${RED}Failed to install fbdev driver!${NC}"; exit 1; }
+cat <<EOF > /etc/X11/xorg.conf.d/99-fbdev.conf
+Section "Device"
+    Identifier "LCD"
+    Driver "fbdev"
+    Option "fbdev" "/dev/fb0"
+EndSection
+Section "Screen"
+    Identifier "Screen0"
+    Device "LCD"
+    DefaultDepth 16  # 16-bit depth for faster refresh on Pi 3B
+    SubSection "Display"
+        Modes "480x320"
+    EndSubSection
+EndSection
+EOF
+cp ./usr/99-calibration
